## A "matrix" object that can cache its inverse. 

## makeCacheMatrix() creates a "matrix" object (in the form of a list) that can
## cache the matrix's inverse.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinv <- function(inverse) inv <<- inverse
    getinv <- function() inv
    list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve() returns the inverse of a matrix (generated by makeMatrix()).
##
## The inverse of a matrix is computed and cached the first time the function is 
## called.
## The function returns the inverse from the cache if it has been calulated,
## and the matrix has not changed.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    
    inv <- x$getinv()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$setinv(inv)
    inv
}
